development:
  adapter: mysql2
  encoding: utf8
  database: LMS_dev
  host: localhost
  username: root
  password:

test:
  adapter: mysql2
  encoding: utf8
  database: LMS_test
  host: localhost
  username: root
  password:

production: 
  adapter: postgresql 
  encoding: unicode